name: First Workflow
on: [workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Hello Justin"
          echo "Trying this pipe feature"
          mkdir hello
      - name: Print Goodbye
        run: echo "Done, thank you"
        
      
